- name: install openjdk-8 repository
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: install common applications
  apt: pkg={{ item }} state=installed
  with_items:
    - wget
    - git
    - curl
    - mc
    - ntpdate
    - multitail
    - openjdk-8-jdk

